services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  WechatWorkSecurityBundle\Command\:
    resource: '../../Command/'
  WechatWorkSecurityBundle\Controller\:
    resource: '../../Controller/'
  WechatWorkSecurityBundle\Repository\:
    resource: '../../Repository/'
  WechatWorkSecurityBundle\Service\:
    resource: '../../Service/'
    public: true
